# Generated by Django 4.0.5 on 2023-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_zip',
            field=models.CharField(max_length=10),
        ),
    ]
